---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users/{user_id}/posts/{post_id}/comments":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    - name: post_id
      in: path
      description: post_id
      required: true
      schema:
        type: string
    get:
      summary: list comments
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      responses:
        '200':
          description: successful
  "/users/{user_id}/posts/{post_id}/comments/{id}":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    - name: post_id
      in: path
      description: post_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete comment
      responses:
        '200':
          description: successful
  "/users/{user_id}/posts":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: list posts
      responses:
        '200':
          description: successful
    post:
      summary: create post
      responses:
        '200':
          description: successful
  "/users/{user_id}/posts/new":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: new post
      responses:
        '200':
          description: successful
  "/users/{user_id}/posts/{id}":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show post
      responses:
        '200':
          description: successful
    delete:
      summary: delete post
      responses:
        '200':
          description: successful
  "/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
  "/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
  "/":
    get:
      summary: list users
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
